config/routes.rb
Rails.application.routes.draw do
  devise_for :users, path: '', path_names: {sign_in: 'login', sign_out: 'logout',sign_up: 'register'}


  #bring all the resource routes for pfolios except show
  resources :pfolios, except: [:show]

  get 'pfolio/:id', to: 'pfolios#show', as: 'pfolio_show'
  get 'angularsorted', to: 'pfolios#angular'

  # get 'pages/about'
  # get 'pages/contact'
  #alternate way
  #get controller/action

  get 'about', to: 'pages#about'
  get 'contact', to: 'pages#contact'


  #we can have custom ones even if we dont have the same file name

  get 'about-me', to: 'pages#about'
  get 'reachus', to: 'pages#contact'



  resources :blogs do
    member do
      get :toggle_status
  end
end

  root to: 'pages#home'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/blog.rb
class Blog < ApplicationRecord
  #by default will be in draft mode, otherwise published
  #can then be used as a method e.g in console do Blog.last.published!
  #we can then also use logic as true and fale when we do Blog.last.published? it returns true
  #or false then can use that shizzz

  enum status: {draft: 0, published: 1}
  extend FriendlyId
  friendly_id :title, use: :slugged

  validates_presence_of :title,:body

  belongs_to :topic
end

app/models/concerns/placeholder.rb
module Placeholder
extend ActiveSupport::Concern

  def self.image_generator(height:,width:)
  "http://via.placeholder.com/#{height}x#{width}"
  end

end

app/models/pfolio.rb
class Pfolio < ApplicationRecord
  has_many :technologies
  accepts_nested_attributes_for :technologies, reject_if: lambda { |attrs| attrs['name'].blank?}

  include Placeholder

  validates_presence_of :title,:body,:main_image,:thumb_image



#2 ways of creating custom methods

  def self.angfilter
    where(subtitle: 'Angular')
  end

  scope :angularfilter, -> {where(subtitle: "Angular")}


#right after pfolio.new has run this procoess auto runs
  after_initialize :set_defaults

  def set_defaults
    self.main_image ||= Placeholder.image_generator(height: '600',width: '400')
    self.thumb_image ||= Placeholder.image_generator(height: '350',width: '150')
  end


  #using just = equals to will overwrite existing
  #using ||= is like writing if image is nill then put else dont


end

app/models/skill.rb
class Skill < ApplicationRecord
  include Placeholder
  validates_presence_of :title,:percent_utilized



#without setting this after initialize it wont by defulat add the image
  after_initialize :set_defaults

  def set_defaults
    self.badge ||= Placeholder.image_generator(height: '250',width: '250')

  end


end

app/models/technology.rb
class Technology < ApplicationRecord
  belongs_to :pfolio
end

app/models/topic.rb
class Topic < ApplicationRecord
  validates_presence_of :title
  has_many :blogs
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable


  validates_presence_of :name

  def first_name
    self.name.split.first
    #can also write as self.name.split[0]
  end

  def last_name
    #can also write as self.name.split[1]
    self.name.split.last
  end


end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  include DeviseWhitelist
  include SetSource


end

app/controllers/blogs_controller.rb
class BlogsController < ApplicationController
  before_action :set_blog, only: [:show, :edit, :update, :destroy, :toggle_status]

  # GET /blogs
  # GET /blogs.json
  def index
    @blogs = Blog.all
  end

  # GET /blogs/1
  # GET /blogs/1.json
  def show
  end

  def toggle_status
    #set to published if draft true
    #@blog.published! if @blog.draft?


    if @blog.draft?
      @blog.published!
    else  @blog.published?
      @blog.draft!
    end

    redirect_to blogs_url, notice: 'Post Status has been updated to : Published'
  end

  # GET /blogs/new
  def new
    @blog = Blog.new
  end

  # GET /blogs/1/edit
  def edit
  end

  # POST /blogs
  # POST /blogs.json
  def create
    @blog = Blog.new(blog_params)

    respond_to do |format|
      if @blog.save
        format.html { redirect_to @blog, notice: 'Blog was successfully created.' }

      else
        format.html { render :new }

      end
    end
  end

  # PATCH/PUT /blogs/1
  # PATCH/PUT /blogs/1.json
  def update
    respond_to do |format|
      if @blog.update(blog_params)
        format.html { redirect_to @blog, notice: 'Blog was successfully updated.' }

      else
        format.html { render :edit }

      end
    end
  end

  # DELETE /blogs/1
  # DELETE /blogs/1.json
  def destroy
    @blog.destroy
    respond_to do |format|
      format.html { redirect_to blogs_url, notice: 'Blog was successfully destroyed.' }

    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_blog
      @blog = Blog.friendly.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def blog_params
      params.require(:blog).permit(:title, :body)
    end
end

app/controllers/concerns/devise_whitelist.rb
module DeviseWhitelist
  extend ActiveSupport::Concern


    included do
      #run this method before you run anything else in the controller only if receiving some devise comm
      before_action :configure_permitted_parameters, if: :devise_controller?
    end

    def configure_permitted_parameters
      devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
      devise_parameter_sanitizer.permit(:account_update, keys: [:name])
    end


end

app/controllers/concerns/set_source.rb
module SetSource
extend ActiveSupport::Concern


    included do
      #run this method before you run anything else in the controller only if receiving some devise comm
      before_action :set_source
    end

    #set it only if params exists, coz we dont want to set it by default
      def set_source
        session[:source] = params[:q] if params[:q]
      end

    #after doing this we have access to q anywhere on the page



end

app/controllers/pages_controller.rb
class PagesController < ApplicationController


  def home
    @posts = Blog.all
    @skills = Skill.all
  end

  def about
  end

  def contact
  end
end

app/controllers/pfolios_controller.rb
class PfoliosController < ApplicationController
  def index
    @portfolio_items = Pfolio.all
  end

  def angular
    @angular_items = Pfolio.angularfilter
  end


  def new

# it doesnt actually create it it just renders the stuff
    @portfolio_item = Pfolio.new
    3.times { @portfolio_item.technologies.build}

  end

  def create
    #perform the lookup
    @portfolio_item = Pfolio.new(pfolio_params)

    #redirect
    respond_to do |format|
      if @portfolio_item.save
        format.html { redirect_to pfolios_path, notice: 'Portfolio item was successfully created.' }

      else
        format.html { render :new }

      end
    end
  end

  def show
    @portfolio_item = Pfolio.find(params[:id])
  end


def edit
  @portfolio_item = Pfolio.find(params[:id])
end

def update
  @portfolio_item = Pfolio.find(params[:id])
  respond_to do |format|
    if @portfolio_item.update(pfolio_params)
      format.html { redirect_to pfolios_path, notice: 'Portfolio was successfully updated.' }

    else
      format.html { render :edit }

    end
  end
end

def destroy
  #perform the lookup
  @portfolio_item = Pfolio.find(params[:id])

  #destroy or delete the record
  @portfolio_item.destroy

  #REDIRECT
  respond_to do |format|
    format.html { redirect_to pfolios_path, notice: 'Portfolio was successfully destroyed.' }

  end
end

def pfolio_params
    params.require(:pfolio).permit(:title,:subtitle,:body,technologies_attributes: [:name])
end


end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/blogs_helper.rb
module BlogsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/pfolios_helper.rb
module PfoliosHelper
end

app/views/blogs/_form.html.erb
<%= form_with(model: blog, local: true) do |form| %>
  <% if blog.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(blog.errors.count, "error") %> prohibited this blog from being saved:</h2>

      <ul>
      <% blog.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>

  <div class="field">
    <%= form.label :body %>
    <%= form.text_area :body %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/blogs/edit.html.erb
<h1>Editing Blog</h1>

<%= render 'form', blog: @blog %>

<%= link_to 'Show', @blog %> |
<%= link_to 'Back', blogs_path %>

app/views/blogs/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Blogs</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Body</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @blogs.each do |blog| %>
      <tr>
        <td><%= blog.title.upcase %></td>
        <td><%= blog.body %></td>
        <td><%= link_to blog.status, toggle_status_blog_path(blog) %></td>

        <td><%= link_to 'Show', blog %></td>
        <td><%= link_to 'Edit', edit_blog_path(blog) %></td>
        <td><%= link_to 'Destroy', blog, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Blog', new_blog_path %>

app/views/blogs/new.html.erb
<h1>New Blog</h1>

<%= render 'form', blog: @blog %>

<%= link_to 'Back', blogs_path %>

app/views/blogs/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @blog.title %>
</p>

<p>
  <strong>Body:</strong>
  <%= @blog.body %>
</p>

<%= link_to 'Edit', edit_blog_path(@blog) %> |
<%= link_to 'Back', blogs_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Portfolio</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
       <p class="notice"><%= notice %></p>
       <p class="alert"><%= alert %></p>

       <% if current_user %>
      <center>First Name: <em><%=current_user.first_name%>  </em> <p>You are logged in as <em> <%=current_user.email  %> </em> </p> </center>
        <%=link_to "Logout",destroy_user_session_path,method: :delete %>
          <%else %>

          <%=link_to "Login",new_user_session_path %>
          <%=link_to "Register",new_user_registration_path %>
          <% end %>

    <%= yield %>



      <% if session[:source]  %>
      <p> Thanks for visiting us from <%=session[:source] %> </p>  
      <%end%>

  </body>
</html>

app/views/pages/about.html.erb
<h1>Pages#about</h1>
<p>Find me in app/views/pages/about.html.erb</p>

app/views/pages/contact.html.erb
<h1>Pages#contact</h1>
<p>Find me in app/views/pages/contact.html.erb</p>

app/views/pages/home.html.erb
<h1>Posts</h1><br>

<%= @posts.inspect %>

<h1>SKILLZ</h1> <br>

<%= @skills.inspect %>

app/views/pfolios/angular.html.erb
<h1> Angular ITEMS </h1>



<% @angular_items.each do |portfolio_item| %>


  <p> <strong> <%= link_to portfolio_item.title , pfolio_show_path(portfolio_item)  %> </strong>  </p>
  <p> <%= portfolio_item.subtitle  %> </p>
  <p> <%= portfolio_item.body  %> </p>
  <%#=  portfolio_item.main_image  %> <br>
  <%= image_tag portfolio_item.thumb_image if !portfolio_item.thumb_image.nil?  %> <br>
  <%= link_to 'Destroy', pfolio_path(portfolio_item), method: :delete, data: { confirm: 'Are you sure?' } %>
  <%#= image_tag portfolio_item.thumb_image unless !portfolio_item.thumb_image.nil?  %>

  <!-- basically saying above if it is not nill then display the image otherwise dont display shit
  for the ones that don;t have the image

  the 2 codes above are the same unless and nill
 -->
 <%=link_to "Edit Portfolio", edit_pfolio_path(portfolio_item.id) %> <br>
 <a href="/pfolios/<%= portfolio_item.id %>/edit"> EDIT WITH A TAGS</a>

 <br>
  <hr>

<% end %>

app/views/pfolios/edit.html.erb
<h1>Edit a new portfolio item</h1>


<!-- form comes here  -->
<%= form_for(@portfolio_item) do |form| %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>
  <div class="field">
    <%= form.label :subtitle %>
    <%= form.text_field :subtitle %>
  </div>

  <div class="field">
    <%= form.label :body %>
    <%= form.text_area :body %>
  </div>

  <!-- <div class="field">
    <%= form.label :main_image %>
    <%= form.text_area :main_image %>
  </div>

  <div class="field">
    <%= form.label :thumb_image%>
    <%= form.text_area :thumb_image %>
  </div> -->

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/pfolios/index.html.erb
<h1> PORTFOLIO ITEMS </h1>


<br>

PATH ->><%= new_pfolio_path %>

<br>

URL ->><%= new_pfolio_url %>

<hr>

<% @portfolio_items.each do |portfolio_item| %>


  <p> <strong> <%= link_to portfolio_item.title , pfolio_show_path(portfolio_item)  %> </strong>  </p>
  <p> <%= portfolio_item.subtitle  %> </p>
  <p> <%= portfolio_item.body  %> </p>
  <%#=  portfolio_item.main_image  %> <br>
  <%= image_tag portfolio_item.thumb_image if !portfolio_item.thumb_image.nil?  %> <br>
  <%= link_to 'Destroy', pfolio_path(portfolio_item), method: :delete, data: { confirm: 'Are you sure?' } %>
  <%#= image_tag portfolio_item.thumb_image unless !portfolio_item.thumb_image.nil?  %>

  <!-- basically saying above if it is not nill then display the image otherwise dont display shit
  for the ones that don;t have the image

  the 2 codes above are the same unless and nill
 -->
 <%=link_to "Edit Portfolio", edit_pfolio_path(portfolio_item.id) %> <br>
 <a href="/pfolios/<%= portfolio_item.id %>/edit"> EDIT WITH A TAGS</a>

 <br>
  <hr>

<% end %>

app/views/pfolios/new.html.erb
<h1>Create a new portfolio item</h1>


<!-- form comes here  -->
<%= form_for(@portfolio_item) do |form| %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>
  <br>
  <div class="field">
    <%= form.label :subtitle %>
    <%= form.text_field :subtitle %>
  </div>

  <br>

  <div class="field">
    <%= form.label :body %>
    <%= form.text_area :body %>
  </div>



  <ul>
    <!-- to use this must have nested attri enabled in .rb file  -->
    <%= form.fields_for :technologies do |technology_form|  %>
    <li>
      <%=technology_form.label :name %>
      <%=technology_form.text_field :name %>
    </li>
    <% end %>
  </ul>

  <!-- <div class="field">
    <%= form.label :main_image %>
    <%= form.text_area :main_image %>
  </div>

  <div class="field">
    <%= form.label :thumb_image%>
    <%= form.text_area :thumb_image %>
  </div> -->

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/pfolios/show.html.erb
<%= image_tag  @portfolio_item.main_image  %> <br>


<h1> <%= @portfolio_item.title %> </h1>

<!-- <%= @portfolio_item.inspect %> -->

<p> <strong> <%= @portfolio_item.title  %> </strong>  </p>
<p> <%= @portfolio_item.subtitle  %> </p>
<p> <%= @portfolio_item.body  %> </p>
<%#=  portfolio_item.main_image  %> <br>
<%#= image_tag portfolio_item.thumb_image if !portfolio_item.thumb_image.nil?  %>


<h2>Technologies Used:</h2>

<% @portfolio_item.technologies.each do |t| %>
<p> <%=t.name%></p>
<% end %>

<hr>

<%= params.inspect  %>

<hr> <br>

<%#= session.inspect  %>


<hr> <br>

PARAMS ID :
<%= params[:id] %>

<br>

this displays the object
Take care of the bracket!

i first did <%#=Pfolio.find(params[:id].technologies) %> -> This shoots an error

Alternate Way: <%=Pfolio.find(params[:id]).technologies %>
<%#=Pfolio.find(params[:id].technologies) %>